# Generated by Django 4.0.3 on 2022-03-25 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneVerify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})"
                            )
                        ],
                    ),
                ),
                ("key", models.IntegerField()),
                ("token", models.CharField(max_length=64, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(null=True)),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "인증",
                "verbose_name_plural": "유저 인증",
                "db_table": "phone_verify",
            },
        ),
    ]
