# Generated by Django 4.0.3 on 2022-03-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_name_alter_user_nickname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email",
            new_name="username",
        ),
    ]
