# Generated by Django 4.0.3 on 2022-03-23 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userverify_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userverify",
            old_name="verified",
            new_name="is_used",
        ),
        migrations.AddField(
            model_name="userverify",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userverify",
            name="token",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userverify",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})"
                    )
                ],
            ),
        ),
    ]
