version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: ./user_demo.dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/user_demo
    env_file:
      - ./.env.development
    ports:
      - "8000:8000"

    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/
    env_file:
      - ./.env.development
    ports:
      - "5432:5432"

volumes:
  app-db-data:
